SELECT
    T.TRANSACTION_HASH,
    T.INCLUDED_IN_BLOCK_HASH,
    T.INCLUDED_IN_CHUNK_HASH,
    T.INDEX_IN_CHUNK,
    T.BLOCK_TIMESTAMP,
    T.SIGNER_ACCOUNT_ID,
    T.SIGNER_PUBLIC_KEY,
    T.NONCE,
    T.RECEIVER_ACCOUNT_ID,
    T.SIGNATURE,
    T.STATUS,
    T.CONVERTED_INTO_RECEIPT_ID,
    T.RECEIPT_CONVERSION_GAS_BURNT,
    T.RECEIPT_CONVERSION_TOKENS_BURNT,
    R.RECEIPT_ID,
    R.INCLUDED_IN_BLOCK_HASH,
    R.INCLUDED_IN_CHUNK_HASH,
    R.INDEX_IN_CHUNK,
    R.INCLUDED_IN_BLOCK_TIMESTAMP,
    R.PREDECESSOR_ACCOUNT_ID,
    R.RECEIVER_ACCOUNT_ID,
    R.RECEIPT_KIND,
    R.ORIGINATED_FROM_TRANSACTION_HASH,
    TA.TRANSACTION_HASH,
    TA.INDEX_IN_TRANSACTION,
    TA.ACTION_KIND,
    TA.ARGS,
    ARA.RECEIPT_ID,
    ARA.INDEX_IN_ACTION_RECEIPT,
    ARA.ACTION_KIND,
    ARA.ARGS,
    ARA.RECEIPT_PREDECESSOR_ACCOUNT_ID,
    ARA.RECEIPT_RECEIVER_ACCOUNT_ID,
    ARA.RECEIPT_INCLUDED_IN_BLOCK_TIMESTAMP,
    B.BLOCK_HEIGHT,
    B.BLOCK_HASH,
    B.PREV_BLOCK_HASH,
    B.BLOCK_TIMESTAMP,
    B.TOTAL_SUPPLY,
    B.GAS_PRICE,
    B.AUTHOR_ACCOUNT_ID,
    EO.RECEIPT_ID,
    EO.EXECUTED_IN_BLOCK_HASH,
    EO.EXECUTED_IN_BLOCK_TIMESTAMP,
    EO.INDEX_IN_CHUNK,
    EO.GAS_BURNT,
    EO.TOKENS_BURNT,
    EO.EXECUTOR_ACCOUNT_ID,
    EO.STATUS,
    EO.SHARD_ID
FROM
    TRANSACTIONS T
    LEFT JOIN RECEIPTS R ON (T.CONVERTED_INTO_RECEIPT_ID = R.RECEIPT_ID
            OR T.TRANSACTION_HASH = R.ORIGINATED_FROM_TRANSACTION_HASH)
    LEFT JOIN TRANSACTION_ACTIONS TA ON T.TRANSACTION_HASH = TA.TRANSACTION_HASH
    LEFT JOIN ACTION_RECEIPT_ACTIONS ARA ON ARA.RECEIPT_ID = R.RECEIPT_ID
    LEFT JOIN BLOCKS B ON B.BLOCK_HASH = R.INCLUDED_IN_BLOCK_HASH
    LEFT JOIN EXECUTION_OUTCOMES EO ON EO.RECEIPT_ID = R.RECEIPT_ID
WHERE
    RECEIPT_PREDECESSOR_ACCOUNT_ID = ANY ($1)
    AND EO.STATUS IN ('SUCCESS_RECEIPT_ID', 'SUCCESS_VALUE')
    AND TO_CHAR(TO_TIMESTAMP(B.BLOCK_TIMESTAMP / 1000000000), 'YYYY-MM-DD"T"HH24:MI:SS"Z"') >= $2
    AND TO_CHAR(TO_TIMESTAMP(B.BLOCK_TIMESTAMP / 1000000000), 'YYYY-MM-DD"T"HH24:MI:SS"Z"') < $3;

